-- MovieTime database schema
-- This file is the single source of truth for a fresh Supabase project.
-- It is safe to run more than once.

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  auth_id text not null unique,
  email text not null unique,
  full_name text,
  display_name text,
  avatar_url text,
  password_hash text,
  bio text,
  favorite_genres text,
  role text not null default 'client',
  list_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.preferences (
  id bigint generated by default as identity primary key,
  profile_id bigint not null unique references public.profiles(id) on delete cascade,
  avatar_index integer not null default 0,
  genres text not null default '',
  content_language text not null default 'pt-BR',
  recommendations_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint preferences_content_language_check
    check (content_language in ('pt-BR', 'en-US', 'es-ES', 'fr-FR', 'de-DE', 'it-IT'))
);

create table if not exists public.watchlist (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  tmdb_id integer not null,
  media_type text not null,
  title text not null default '',
  poster_url text,
  backdrop_url text,
  added_at timestamptz not null default now(),
  constraint watchlist_media_type_check check (media_type in ('movie', 'tv', 'series')),
  constraint watchlist_item_unique unique (profile_id, tmdb_id, media_type)
);

create table if not exists public.watch_history (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  tmdb_id integer not null,
  media_type text not null,
  title text not null default '',
  poster_url text,
  backdrop_url text,
  season_number integer not null default 0,
  episode_number integer not null default 0,
  total_seasons integer not null default 0,
  total_episodes integer not null default 0,
  season_episodes integer not null default 0,
  progress_percent real not null default 0,
  watched_at timestamptz not null default now(),
  constraint watch_history_media_type_check check (media_type in ('movie', 'tv', 'series')),
  constraint watch_history_item_unique unique (
    profile_id, tmdb_id, season_number, episode_number, media_type
  )
);

create table if not exists public.ratings (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  tmdb_id integer not null,
  media_type text not null,
  value text not null,
  created_at timestamptz not null default now(),
  constraint ratings_value_check check (value in ('love', 'like', 'dislike')),
  constraint ratings_item_unique unique (profile_id, tmdb_id, media_type)
);


create table if not exists public.app_releases (
  id bigint generated by default as identity primary key,
  version_name text not null,
  version_code integer not null,
  apk_path text not null,
  file_name text not null default 'movietime.apk',
  file_size_bytes bigint,
  release_notes text not null default '',
  mandatory boolean not null default false,
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  constraint app_releases_version_code_unique unique (version_code),
  constraint app_releases_version_name_not_empty check (length(trim(version_name)) > 0),
  constraint app_releases_apk_path_not_empty check (length(trim(apk_path)) > 0)
);

-- Repair columns when this schema is applied to an older MovieTime database.
alter table public.profiles add column if not exists list_name text;
alter table public.preferences add column if not exists content_language text not null default 'pt-BR';
alter table public.watch_history add column if not exists season_episodes integer not null default 0;

create unique index if not exists watchlist_item_unique_idx
  on public.watchlist (profile_id, tmdb_id, media_type);
create unique index if not exists watch_history_item_unique_idx
  on public.watch_history (profile_id, tmdb_id, season_number, episode_number, media_type);
create unique index if not exists ratings_item_unique_idx
  on public.ratings (profile_id, tmdb_id, media_type);
create unique index if not exists app_releases_one_active_idx
  on public.app_releases (is_active)
  where is_active = true;

alter table public.profiles enable row level security;
alter table public.preferences enable row level security;
alter table public.watchlist enable row level security;
alter table public.watch_history enable row level security;
alter table public.ratings enable row level security;
alter table public.app_releases enable row level security;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'app-releases', 'app-releases', true, 524288000,
  array['application/vnd.android.package-archive']::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Public download of the release APK. Upload permissions stay server-side.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'app_releases'
      and policyname = 'public can read active app release'
  ) then
    create policy "public can read active app release"
      on public.app_releases for select to anon, authenticated
      using (is_active = true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'public can read app release files'
  ) then
    create policy "public can read app release files"
      on storage.objects for select to anon, authenticated
      using (bucket_id = 'app-releases');
  end if;
end $$;
