create table if not exists public.app_releases (
  id bigint generated by default as identity primary key,
  version_name text not null,
  version_code integer not null,
  apk_path text not null,
  file_name text not null default 'movietime.apk',
  file_size_bytes bigint,
  release_notes text not null default '',
  mandatory boolean not null default false,
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  constraint app_releases_version_code_unique unique (version_code),
  constraint app_releases_version_name_not_empty check (length(trim(version_name)) > 0),
  constraint app_releases_apk_path_not_empty check (length(trim(apk_path)) > 0)
);

create unique index if not exists app_releases_one_active_idx
  on public.app_releases (is_active)
  where is_active = true;

alter table public.app_releases enable row level security;

create policy "public can read active app release"
  on public.app_releases
  for select to anon, authenticated
  using (is_active = true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'app-releases', 'app-releases', true, 524288000,
  array['application/vnd.android.package-archive']::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "public can read app release files"
  on storage.objects
  for select to anon, authenticated
  using (bucket_id = 'app-releases');